openapi: 3.2.0
info:
  title: Opply Canny API
  version: 0.0.0
tags:
- name: Canny
paths:
  /api/v1/canny/generate-token/:
    get:
      operationId: api_v1_canny_generate_token_retrieve
      tags:
      - Canny
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CannyTokenResponse'
          description: ''
      summary: Api v1 canny generate token retrieve
      x-summary-source: derived
components:
  schemas:
    CannyTokenResponse:
      type: object
      properties:
        token:
          type: string
      required:
      - token
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
